




###
GET http://localhost:5000/api/proveedor/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjYTJjOWU1LWFhNjEtNDU5YS1iNzg0LTBiMDM5NGVmN2QwMiIsImlhdCI6MTYyNTMyMjQ5OCwiZXhwIjoxNjI1MzI4NDk4fQ.R0-Sbf6XBxHxXzPlztEjcnMukH0K9zJu8YrmIZFIiVc


###
GET http://localhost:5000/api/insumo/d57132eb-db39-442d-860a-38c4b2701f88 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjYTJjOWU1LWFhNjEtNDU5YS1iNzg0LTBiMDM5NGVmN2QwMiIsImlhdCI6MTYyNTMyMjQ5OCwiZXhwIjoxNjI1MzI4NDk4fQ.R0-Sbf6XBxHxXzPlztEjcnMukH0K9zJu8YrmIZFIiVc


###
GET http://localhost:5000/api/proveedor/dd3caa27-958a-4abf-949a-7101b77c547a HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjYTJjOWU1LWFhNjEtNDU5YS1iNzg0LTBiMDM5NGVmN2QwMiIsImlhdCI6MTYyNTMyMjQ5OCwiZXhwIjoxNjI1MzI4NDk4fQ.R0-Sbf6XBxHxXzPlztEjcnMukH0K9zJu8YrmIZFIiVc



###

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "sam",
    "password": "zinedine"
}
